### ISSUE TITLE
Question: Is it possible to add this to a desktop markdown editor? 

### ISSUE THREAD

**Issue by trueschool** [jjuliano/markdown-ui#9]
Thanks for creating this. I'm excited by the idea, but I haven't really tried it out yet because I'm used to working in a desktop MD editor (MacDown, HarooPad, and Atom are my faves). I would like to explore it, but I don't get how to reconcile it with my workflow. 

I'd love to be able to work in a comfortable markdown-oriented editor where I can see the preview alongside, and possibly have keystrokes or menu items (or even text suggestions -- I think this is possible in Atom) to help with learning the new MD commands. 

Please let me know if I'm totally barking up the wrong tree. I think this project has a lot of potential, and I think it would be extremely successful in a UI that meets less techie users halfway. 

Thanks again for such an innovative and useful idea!
Ted

**Comment by sjoerd222888** [comment]
This would be awesome. Unfortunately it is now 2019 and we have no answer yet...

**Comment by jjuliano** [comment]
Thanks for reaching out, and having interests on the project.

The `next` branch contains the new changes where the goal is make it non-framework specific.
I think this feature will be the most important feature to support other frameworks.
I am not actively maintaining the project at the moment since I have many responsibilities on real life.
You are free to fork the project and shape it on whatever form you need it.
